name: Lint
on:
  pull_request:
    types: [synchronize, opened, edited]
jobs:
  go:
    name: Lint Go
    uses: bruxisma/actions/.github/workflows/go.lint.yml@main
  yaml:
    name: Lint YAML
    uses: bruxisma/actions/.github/workflows/yaml.lint.yml@main
  actions:
    name: Lint GitHub Action Workflows
    uses: bruxisma/actions/.github/workflows/actions.lint.yml@main
  spellcheck:
    name: Spellcheck
    uses: bruxisma/actions/.github/workflows/spellcheck.yml@main
