name: Tests
on:
  push:
    branches: main
  workflow_call:
jobs:
  test:
    permissions:
      id-token: write
      checks: read
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version-file: ${{github.workspace}}/go.mod
          cache: true
      - name: Setup gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{github.token}}
      - name: Run Tests
        run: >-
          go test -v ./...
          -json
          -coverprofile coverage.out
          -cover ${{github.workspace}}
          2>&1 | gotestfmt
      - name: Upload Code Coverage
        uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
        with:
          fail_ci_if_error: true
          directory: ${{github.workspace}}
          files: coverage.out
          use_oidc: true
