name: Tests
on:
  push:
    branches: main
  workflow_call:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - name: Setup Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4
        with:
          go-version-file: ${{github.workspace}}/go.mod
          cache: true
      - name: Setup gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{github.token}}
      - name: Run Tests
        run: >-
          go test -v ./...
          -json
          -coverprofile coverage.out
          -cover ${{github.workspace}}
          2>&1 | gotestfmt
      - name: Upload Code Coverage
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          fail_ci_if_error: true
          directory: ${{github.workspace}}
          files: coverage.out
