name: Tests
on:
  push:
    branches: main
  workflow_call:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
        with:
          go-version-file: ${{github.workspace}}/go.mod
          cache: true
      - name: Setup gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{github.token}}
      - name: Run Tests
        run: >-
          go test -v ./...
          -json
          -coverprofile coverage.out
          -cover ${{github.workspace}}
          2>&1 | gotestfmt
      - name: Upload Code Coverage
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3.1.1
        with:
          fail_ci_if_error: true
          directory: ${{github.workspace}}
          files: coverage.out
